In [1]:
print("Hello World!! Let's start the Journey of Machine Learning")

Hello World!! Let's start the Journey of Machine Learning


# NUMPY Tutorial
--This Notebook explores various different functions of the numpy Library

In [2]:
import numpy as np

In [3]:
x=np.array([2,3,4,5])
print(x)
print(type(x))

[2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
y=np.array(['Jalaj', '20', 'Engineer', '$Billionaire'])
print(y)

['Jalaj' '20' 'Engineer' '$Billionaire']


#### numpy.linspace(start,stop)
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval 
[start, stop]

The endpoint of the interval can optionally be excluded.

In [5]:
b=np.linspace(0,20,10,False,True)
b

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), np.float64(2.0))

In [6]:
c=np.ones((3,4),str)
c

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [7]:
c=np.zeros((3,4),int)
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
p=np.random.rand(3,4)
p

array([[0.84672896, 0.65659858, 0.83405798, 0.33999022],
       [0.99560761, 0.00524615, 0.35917884, 0.95018345],
       [0.68532043, 0.25340893, 0.62982122, 0.52197492]])

In [9]:
p=np.eye(3)
p

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
k=np.arange(1,10,1)
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
y=k.reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
y.shape

(3, 3)

In [13]:
y=np.arange(11,20,1)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
z=np.add(k,y)
z

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [15]:
z=np.multiply(k,y)
z

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [16]:
z=np.divide(k,y)
z

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [17]:
z=np.subtract(k,y)
z

array([-10, -10, -10, -10, -10, -10, -10, -10, -10])

In [18]:
z=np.remainder(k,y)
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
k[1]

np.int64(2)

In [20]:
k[1:5]

array([2, 3, 4, 5])

In [21]:
k[5:]

array([6, 7, 8, 9])

In [22]:
k[-3:-1]

array([7, 8])

In [23]:
o=np.array([[1,2,3],[4,5,6],[7,8,9]])
o

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
o[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [25]:
p=o.copy()
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a=o
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
p[0,0]=100
p

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [28]:
a[0,0]=31
a

array([[31,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
o[0,1]=200
o

array([[ 31, 200,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [30]:
a

array([[ 31, 200,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [31]:
p

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [32]:
x=np.append(p,[[10,11,12]],axis=0)
x

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12]])

In [33]:
x=np.append(x,[[13],[14],[15],[16]],axis=1)
x

array([[100,   2,   3,  13],
       [  4,   5,   6,  14],
       [  7,   8,   9,  15],
       [ 10,  11,  12,  16]])

In [34]:
x=np.insert(x,1,[17,18,19,20],axis=0)
x

array([[100,   2,   3,  13],
       [ 17,  18,  19,  20],
       [  4,   5,   6,  14],
       [  7,   8,   9,  15],
       [ 10,  11,  12,  16]])

In [35]:
x=np.insert(x,1,[21,22,23,24,25],axis=1)
x

array([[100,  21,   2,   3,  13],
       [ 17,  22,  18,  19,  20],
       [  4,  23,   5,   6,  14],
       [  7,  24,   8,   9,  15],
       [ 10,  25,  11,  12,  16]])

In [36]:
j=x.reshape(5,5)
j

array([[100,  21,   2,   3,  13],
       [ 17,  22,  18,  19,  20],
       [  4,  23,   5,   6,  14],
       [  7,  24,   8,   9,  15],
       [ 10,  25,  11,  12,  16]])

In [37]:
x=np.matrix("1,2,3;4,5,6;7,8,9")
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
a=np.arange(0,20,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
j=a.reshape(5,4)
j

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [40]:
j=np.matrix(j)
j

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [41]:
b=np.linspace(0,30,20,True,False)
b

array([ 0.        ,  1.57894737,  3.15789474,  4.73684211,  6.31578947,
        7.89473684,  9.47368421, 11.05263158, 12.63157895, 14.21052632,
       15.78947368, 17.36842105, 18.94736842, 20.52631579, 22.10526316,
       23.68421053, 25.26315789, 26.84210526, 28.42105263, 30.        ])

In [42]:
b=b.reshape(5,4)
b

array([[ 0.        ,  1.57894737,  3.15789474,  4.73684211],
       [ 6.31578947,  7.89473684,  9.47368421, 11.05263158],
       [12.63157895, 14.21052632, 15.78947368, 17.36842105],
       [18.94736842, 20.52631579, 22.10526316, 23.68421053],
       [25.26315789, 26.84210526, 28.42105263, 30.        ]])

In [43]:
b=np.matrix(b)
b

matrix([[ 0.        ,  1.57894737,  3.15789474,  4.73684211],
        [ 6.31578947,  7.89473684,  9.47368421, 11.05263158],
        [12.63157895, 14.21052632, 15.78947368, 17.36842105],
        [18.94736842, 20.52631579, 22.10526316, 23.68421053],
        [25.26315789, 26.84210526, 28.42105263, 30.        ]])

In [44]:
b=np.transpose(b)
b

matrix([[ 0.        ,  6.31578947, 12.63157895, 18.94736842, 25.26315789],
        [ 1.57894737,  7.89473684, 14.21052632, 20.52631579, 26.84210526],
        [ 3.15789474,  9.47368421, 15.78947368, 22.10526316, 28.42105263],
        [ 4.73684211, 11.05263158, 17.36842105, 23.68421053, 30.        ]])

In [45]:
f=np.dot(j,b)
f

matrix([[  22.10526316,   60.        ,   97.89473684,  135.78947368,
          173.68421053],
        [  60.        ,  198.94736842,  337.89473684,  476.84210526,
          615.78947368],
        [  97.89473684,  337.89473684,  577.89473684,  817.89473684,
         1057.89473684],
        [ 135.78947368,  476.84210526,  817.89473684, 1158.94736842,
         1500.        ],
        [ 173.68421053,  615.78947368, 1057.89473684, 1500.        ,
         1942.10526316]])

In [46]:
np.linalg.det(f)

np.float64(0.0)

In [47]:
rank = np.linalg.matrix_rank(f)
rank

np.int64(2)